---

- name: Installing dependencies
  apt:
    pkg: "{{ nodejs_dependencies }}"
    state: present

- name: Adding APT key
  apt_key:
    url: "{{ nodejs_repo_key }}"
    state: present

- name: Adding APT repository
  apt_repository:
    repo: "{{ nodejs_repo }}"
    update_cache: yes

- name: Installing packages
  apt:
    pkg: "{{ nodejs_package }}"
    state: present
