---

- name: Installing packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - nodejs
  tags:
    - web
    - nodejs
    - install

- name: Updating packages
  command: npm update -g
  tags:
    - web
    - nodejs
    - install
